name: local
variables:
  - name: BASE_URL
    value: http://localhost:3000
    description: ""
  - name: TOKEN
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkR2QjBZMlFHbEZ5d01mQndBa0JlNCJ9.eyJpc3MiOiJodHRwczovL2Rldi03ZXh2ZTV0Y2Z1MG10MWF1LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ3bGZIdlNCc3BscnM2N1h5Slh1MEVjdExvaFZwWWlGWkBjbGllbnRzIiwiYXVkIjoibXlUcmlwTWluZC1hcGktZGV2IiwiaWF0IjoxNzkwMTQ4OTI4LCJleHAiOjE3OTAyMzUzMjgsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IndsZkh2U0JzcGxyczY3WHlKWHUwRWN0TG9oVnBZaUZaIn0.POvrK8jFQ0iytpzrTLRIkVDALIe672V77RZIGtP5YO7-3PN4Rn6Br9NGozzpS-ih9koGoz-Cn4sMTVJf0wqeF_TyZkBXYFVAkHQ_cEw8m_3gqTxYkQOxlxvFwM7MByBCwn8aP6XyVqjlAt9Gqqp3zaFk8iU3Z0j68PeTta1nrkqTEJAv3Q__aLEyezOAK_Nho2150u9NMxjAPnMPvqqUwh9CcSJL5jNQ4crPwmeJac8ElZ8DpwbON_saB4F0C9ReUF_kxHwBaiuJur4Bg-PpHfUpT-UXg3TBjrp9oHFJLU92h_Ng4eUSoXAQYYbBVRiPBVY2hZi8SawHZ-zQ7xK2lg
    description: ""
