name: local
variables:
  - name: BASE_URL
    value: http://localhost:3000
  - name: TOKEN
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkR2QjBZMlFHbEZ5d01mQndBa0JlNCJ9.eyJpc3MiOiJodHRwczovL2Rldi03ZXh2ZTV0Y2Z1MG10MWF1LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ3bGZIdlNCc3BscnM2N1h5Slh1MEVjdExvaFZwWWlGWkBjbGllbnRzIiwiYXVkIjoibXlUcmlwTWluZC1hcGktZGV2IiwiaWF0IjoxNzkxMDE1MjE5LCJleHAiOjE3OTExMDE2MTksImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IndsZkh2U0JzcGxyczY3WHlKWHUwRWN0TG9oVnBZaUZaIn0.jeRZPB8i67gPJlgjbaQ-DN454SbCxmXSYEeHdHNNkXsK-j5yFKlvam7C5sj5NUpvDfBPcsXFVq_Bh6TUxTPs9rorkSuQFAR4Atq2yNajcHxeTzjAaZUmbze6BVkwyNhLvRdMg1eF0bHRYDnUgs5UyvbkBDmysmjpwlxn3SsN9gz4q7-UItCxEEhwU6XVPEtKZABWu_UuObihvmUzNwQC7DVWA-72v7GWS9H2mMSMF1qkFyDbysZ4zLSUZgBbMJeqlToxA6Xp7o4DmQuEfKmYhFt29e4qrg0tGnjlKZKGkXGlxifU6JyKpYVY2nfnRTTK6-05jpUDGgpcRqfUH0HSrA
